

name: Docker action

on: 
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Tag'
        required: true

jobs:
  login::
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
      	with: 
	  username: ${{ secrets.DOCKERHUB_USERNAME }}
	  password: ${{ secrets.DOCKERHUB_TOKEN }}


